version: "3.9"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200
    ports:
      - "5432:5432"
    volumes:
      # copy the sql script to configure for the integration
      - ./sql/01_configure_postgres.sh:/docker-entrypoint-initdb.d/01_configure_postgres.sh
      # Use sample table and data from https://github.com/shabuhabs/javashop-otel/tree/workshop/db
      - ./sql/02_create_table.sql:/docker-entrypoint-initdb.d/02_create_table.sql
      - ./sql/03_fill_table.sql:/docker-entrypoint-initdb.d/03_fill_table.sql
  splunk-otel-collector:
    image: quay.io/signalfx/splunk-otel-collector:latest
    environment:
      - SPLUNK_ACCESS_TOKEN=${SPLUNK_ACCESS_TOKEN}
      - SPLUNK_REALM=${SPLUNK_REALM}
      - SPLUNK_API_URL=https://api.${SPLUNK_REALM}.signalfx.com
      - SPLUNK_BUNDLE_DIR=/usr/lib/splunk-otel-collector/agent-bundle
      - SPLUNK_COLLECTD_DIR=/usr/lib/splunk-otel-collector/agent-bundle/run/collectd
      - SPLUNK_HEC_TOKEN=${SPLUNK_ACCESS_TOKEN}
      - SPLUNK_HEC_URL=https://ingest.${SPLUNK_REALM}.signalfx.com/v1/log
      - SPLUNK_INGEST_URL=https://ingest.${SPLUNK_REALM}.signalfx.com
      - SPLUNK_TRACE_URL=https://ingest.${SPLUNK_REALM}.signalfx.com/v2/trace
      - SPLUNK_CONFIG=/config/postgresql.yaml
    volumes:
      - ./config:/config
    ports:
      - "13133:13133"
      - "14250:14250"
      - "14268:14268"
      - "4317:4317"
      - "6060:6060"
      - "7276:7276"
      - "8888:8888"
      - "9080:9080"
      - "9411:9411"
      - "9943:9943"
